# Site settings
title: Andrew J Hahn
email: andyjhahn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front end web development in the Twin Cities. Team leadership and training enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewjhahn.com" # the base hostname & protocol for your site
twitter_username: runningrhetoric
github_username:  runningrhetoric

# Build settings
markdown: kramdown

